name: Build and Tag

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Add execution right to gradlew
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android SDK
        run: sdkmanager "platform-tools" "platforms;android-34"

      - name: Build the app
        run: ./gradlew build --no-daemon --stacktrace --info --scan

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease
  tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
      - uses: actions/checkout@v4